project:
  type: website
  output-dir: docs

website:
  title: "Marina Scalon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - R Lessons.qmd
      - TidyTuesday.qmd


format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true



