project:
  type: website
  output-dir: docs

website:
  title: "Marina Scalon"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: " "
        icon: house-fill
      - publications.qmd
      - TidyTuesday.qmd
      - sidebar:aulas

  sidebar:
  - id: aulas
    title: "Aulas 2024 (Português)"
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - aulas/Aula Quarto.qmd
      - aulas/Pratica_Semana2.qmd
      - aulas/Pratica_Semana3.qmd
      - aulas/Pratica_Semana3_Parte2.qmd
      - aulas/Aula_Mapa.qmd

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true



